"""create all tables

Revision ID: 4a129036b96f
Revises: 
Create Date: 2026-03-20 02:26:08.262677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a129036b96f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('resend_inbound_address', sa.String(length=255), nullable=True),
    sa.Column('sending_domain_status', sa.String(length=20), nullable=False),
    sa.Column('first_import_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_import_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_recovered_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('vat_id', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=True),
    sa.Column('total_outstanding', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('invoice_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_invoice_date', sa.Date(), nullable=True),
    sa.Column('merge_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_account_id'), 'customers', ['account_id'], unique=False)
    op.create_index(op.f('ix_customers_normalized_name'), 'customers', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_customers_vat_id'), 'customers', ['vat_id'], unique=False)
    op.create_table('import_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delimiter', sa.String(length=5), nullable=True),
    sa.Column('date_format', sa.String(length=30), nullable=True),
    sa.Column('number_format', sa.String(length=20), nullable=True),
    sa.Column('encoding', sa.String(length=30), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_templates_account_id'), 'import_templates', ['account_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('import_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('original_file_path', sa.String(length=500), nullable=True),
    sa.Column('email_sender', sa.String(length=255), nullable=True),
    sa.Column('email_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resend_email_id', sa.String(length=100), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('rows_found', sa.Integer(), nullable=False),
    sa.Column('invoices_created', sa.Integer(), nullable=False),
    sa.Column('invoices_updated', sa.Integer(), nullable=False),
    sa.Column('invoices_disappeared', sa.Integer(), nullable=False),
    sa.Column('invoices_unchanged', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('warnings_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('change_set', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parse_duration_ms', sa.Integer(), nullable=True),
    sa.Column('mapping_method', sa.String(length=20), nullable=True),
    sa.Column('mapping_confidence', sa.Float(), nullable=True),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['import_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_records_account_id'), 'import_records', ['account_id'], unique=False)
    op.create_index('ix_imports_account_status', 'import_records', ['account_id', 'status'], unique=False)
    op.create_index('ix_imports_file_hash', 'import_records', ['account_id', 'file_hash'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('normalized_invoice_number', sa.String(length=100), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('first_overdue_at', sa.Date(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('last_action_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('next_action_type', sa.String(length=50), nullable=True),
    sa.Column('action_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_import_id', sa.UUID(), nullable=True),
    sa.Column('last_updated_import_id', sa.UUID(), nullable=True),
    sa.Column('recovery_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovery_import_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['first_seen_import_id'], ['import_records.id'], ),
    sa.ForeignKeyConstraint(['last_updated_import_id'], ['import_records.id'], ),
    sa.ForeignKeyConstraint(['recovery_import_id'], ['import_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_account_due', 'invoices', ['account_id', 'due_date'], unique=False)
    op.create_index('ix_invoices_account_invoice_num', 'invoices', ['account_id', 'normalized_invoice_number'], unique=False)
    op.create_index('ix_invoices_account_status', 'invoices', ['account_id', 'status'], unique=False)
    op.create_index('ix_invoices_next_action', 'invoices', ['account_id', 'next_action_date'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('import_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['import_records.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activities_account_created', 'activities', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_activities_customer', 'activities', ['customer_id', 'created_at'], unique=False)
    op.create_index('ix_activities_invoice', 'activities', ['invoice_id', 'created_at'], unique=False)
    op.create_index('ix_activities_type', 'activities', ['account_id', 'action_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activities_type', table_name='activities')
    op.drop_index('ix_activities_invoice', table_name='activities')
    op.drop_index('ix_activities_customer', table_name='activities')
    op.drop_index('ix_activities_account_created', table_name='activities')
    op.drop_table('activities')
    op.drop_index('ix_invoices_next_action', table_name='invoices')
    op.drop_index('ix_invoices_account_status', table_name='invoices')
    op.drop_index('ix_invoices_account_invoice_num', table_name='invoices')
    op.drop_index('ix_invoices_account_due', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_imports_file_hash', table_name='import_records')
    op.drop_index('ix_imports_account_status', table_name='import_records')
    op.drop_index(op.f('ix_import_records_account_id'), table_name='import_records')
    op.drop_table('import_records')
    op.drop_table('users')
    op.drop_index(op.f('ix_import_templates_account_id'), table_name='import_templates')
    op.drop_table('import_templates')
    op.drop_index(op.f('ix_customers_vat_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_normalized_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_account_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('accounts')
    # ### end Alembic commands ###
